name: cabal

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["8.6", "8.8", "8.10"]
        cabal: ["3.2"]
        cache-version: ["2021-01-05"]

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache cabal
      uses: actions/cache@v2
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cache-version }}-cabal
        
    - name: Build
      run: |
        cabal build
        cabal install all:exes --overwrite-policy=always